model_params:  
  descrip: "Pix2Pix, training on 320x240. 4 encoder and Decoder. Same to same Pix2Pix"
  model_name: "my-net" # DD or MSCNN or AOD
  mode: "train"   # train or test
  log_dir: /media/mnt/dehaze/mynet_logs/ # path to write the model and load the model

training_params:
  learning_rate: 1e-04
  epochs: 200
  batch_size: 32
  # data_path: /media/mnt/dehaze/data/ChinaMM18dehaze/  # Path from where to load the data
  data_path: /media/mnt/dehaze/data/cityscape/processed/
